### ISSUE TITLE
Error to run 'amb -n npm -g install @vue/cli'

### ISSUE THREAD

**Issue by josejlpp** [ambientum/ambientum#120]
when I run this line:
amb -n npm -g install @vue/cli

I received this error
```
/usr/local/lib/node_modules/@ambientum/cli/dist/support/docker/run.js:87
    container.attach(finalAttachOptions, (err, stream) => {
              ^

TypeError: Cannot read property 'attach' of null
    at _docker.default.createContainer (/usr/local/lib/node_modules/@ambientum/cli/dist/support/docker/run.js:87:15)
    at /usr/local/lib/node_modules/@ambientum/cli/node_modules/dockerode/lib/docker.js:73:23
    at /usr/local/lib/node_modules/@ambientum/cli/node_modules/docker-modem/lib/modem.js:265:7
    at getCause (/usr/local/lib/node_modules/@ambientum/cli/node_modules/docker-modem/lib/modem.js:287:7)
    at Modem.buildPayload (/usr/local/lib/node_modules/@ambientum/cli/node_modules/docker-modem/lib/modem.js:256:5)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/@ambientum/cli/node_modules/docker-modem/lib/modem.js:232:14)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
```

Setup:
Node v8.10.0
NPM 3.5.2
OS ubuntu 18.04

**Comment by josejlpp** [comment]
It was the image npm, the LTS version is in error
