### ISSUE TITLE
TypeError: Cannot read property 'attach' of null

### ISSUE THREAD

**Issue by franciscoprado** [ambientum/ambientum#121]
When I run the code
`amb -p composer create laravel/laravel my-project`

I get the following error and the project is not build.
`/usr/local/lib/node_modules/@ambientum/cli/dist/support/docker/run.js:87
    container.attach(finalAttachOptions, (err, stream) => {
              ^

TypeError: Cannot read property 'attach' of null
    at _docker.default.createContainer (/usr/local/lib/node_modules/@ambientum/cli/dist/support/docker/run.js:87:15)
    at /usr/local/lib/node_modules/@ambientum/cli/node_modules/dockerode/lib/docker.js:73:23
    at /usr/local/lib/node_modules/@ambientum/cli/node_modules/docker-modem/lib/modem.js:265:7
    at getCause (/usr/local/lib/node_modules/@ambientum/cli/node_modules/docker-modem/lib/modem.js:287:7)
    at Modem.buildPayload (/usr/local/lib/node_modules/@ambientum/cli/node_modules/docker-modem/lib/modem.js:256:5)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/@ambientum/cli/node_modules/docker-modem/lib/modem.js:232:14)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)`

**Comment by ricardobarantini** [comment]
Same problem here

**Comment by hrmsautran** [comment]
Same problem here

**Comment by profalves** [comment]
Same problem here. And still not fixed :/

**Comment by fernandotugu** [comment]
same problem yet.
